VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Series"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Name As String
Public ElementNames As Object
Public Dim1_Data As Object
Public Dim2_Data As Object
Public Dim3_Data As Object

'Public Sub SetElementNames(obj)
'Set ElementNames = obj
'End Sub
'
'Public Function GetElementNames() As Object
'Set GetElementNames = ElementNames
'End Function
'
'Public Sub SetDim1_Data(obj)s
'Set Dim1_Data = obj
'End Sub
'
'Public Sub SetDim2_Data(obj)
'Set Dim2_Data = obj
'End Sub
'
'Public Sub SetDim3_Data(obj)
'Set Dim3_Data = obj
'End Sub
'
'Public Function GetDim1_Data() As Object
'Set GetDim1_Data = Dim1_Data
'End Function
'
'Public Function GetDim2_Data() As Object
'Set GetDim2_Data = Dim2_Data
'End Function
'
'Public Function GetDim3_Data() As Object
'Set GetDim3_Data = Dim3_Data
'End Function
